blank_issues_enabled: false
contact_links:
  - name: â—Only for Umbraco HQ team members
    url: https://github.com/umbraco/Umbraco-CMS/
    about: Do not post issues in this repo. Use umbraco/Umbraco-CMS instead.
